# Generated by Django 3.1 on 2020-08-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_appinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('filePath', models.TextField()),
                ('fileName', models.TextField()),
                ('fileSize', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('nid', models.BigIntegerField()),
            ],
        ),
    ]
