# Generated by Django 3.1 on 2020-08-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bigfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('coustDetail', models.TextField()),
                ('costTime', models.TextField()),
            ],
        ),
    ]
