# Generated by Django 3.1 on 2020-08-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_appstart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('Detail', models.TextField()),
                ('blockTime', models.IntegerField()),
                ('page', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='leak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('Detail', models.TextField()),
                ('page', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pageLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('time', models.TextField()),
                ('page', models.TextField()),
                ('trace', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='uiLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('detail', models.TextField()),
                ('level', models.TextField()),
                ('page', models.TextField()),
            ],
        ),
    ]
