# Generated by Django 3.1 on 2020-08-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_block_leak_pageload_uilevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.TextField()),
                ('pagekey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CpuValuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.BigIntegerField()),
                ('time', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fps',
            fields=[
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.TextField()),
                ('pagekey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='fpsValuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.BigIntegerField()),
                ('time', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.TextField()),
                ('pagekey', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='memoryValuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.BigIntegerField()),
                ('time', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='network',
            fields=[
                ('did', models.BigIntegerField()),
                ('ihao', models.TextField()),
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('page', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='networkValuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.BigIntegerField()),
                ('time', models.TextField()),
                ('code', models.TextField()),
                ('down', models.TextField()),
                ('method', models.TextField()),
                ('up', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
